// Canonical reference data for the 114 Surahs of the Quran (standard Uthmani ayah counts).
// Used by SurahsService.importCanonical() to seed/upsert the Surah table.
export interface CanonicalSurah {
  number: number;
  nameArabic: string;
  nameEnglish: string;
  totalAyahs: number;
  revelationType: 'Meccan' | 'Medinan';
}

export const CANONICAL_SURAHS: CanonicalSurah[] = [
  { number: 1, nameArabic: 'الفاتحة', nameEnglish: 'Al-Fatihah', totalAyahs: 7, revelationType: 'Meccan' },
  { number: 2, nameArabic: 'البقرة', nameEnglish: 'Al-Baqarah', totalAyahs: 286, revelationType: 'Medinan' },
  { number: 3, nameArabic: 'آل عمران', nameEnglish: 'Aal-E-Imran', totalAyahs: 200, revelationType: 'Medinan' },
  { number: 4, nameArabic: 'النساء', nameEnglish: 'An-Nisa', totalAyahs: 176, revelationType: 'Medinan' },
  { number: 5, nameArabic: 'المائدة', nameEnglish: "Al-Ma'idah", totalAyahs: 120, revelationType: 'Medinan' },
  { number: 6, nameArabic: 'الأنعام', nameEnglish: "Al-An'am", totalAyahs: 165, revelationType: 'Meccan' },
  { number: 7, nameArabic: 'الأعراف', nameEnglish: "Al-A'raf", totalAyahs: 206, revelationType: 'Meccan' },
  { number: 8, nameArabic: 'الأنفال', nameEnglish: 'Al-Anfal', totalAyahs: 75, revelationType: 'Medinan' },
  { number: 9, nameArabic: 'التوبة', nameEnglish: 'At-Tawbah', totalAyahs: 129, revelationType: 'Medinan' },
  { number: 10, nameArabic: 'يونس', nameEnglish: 'Yunus', totalAyahs: 109, revelationType: 'Meccan' },
  { number: 11, nameArabic: 'هود', nameEnglish: 'Hud', totalAyahs: 123, revelationType: 'Meccan' },
  { number: 12, nameArabic: 'يوسف', nameEnglish: 'Yusuf', totalAyahs: 111, revelationType: 'Meccan' },
  { number: 13, nameArabic: 'الرعد', nameEnglish: "Ar-Ra'd", totalAyahs: 43, revelationType: 'Medinan' },
  { number: 14, nameArabic: 'ابراهيم', nameEnglish: 'Ibrahim', totalAyahs: 52, revelationType: 'Meccan' },
  { number: 15, nameArabic: 'الحجر', nameEnglish: 'Al-Hijr', totalAyahs: 99, revelationType: 'Meccan' },
  { number: 16, nameArabic: 'النحل', nameEnglish: 'An-Nahl', totalAyahs: 128, revelationType: 'Meccan' },
  { number: 17, nameArabic: 'الإسراء', nameEnglish: 'Al-Isra', totalAyahs: 111, revelationType: 'Meccan' },
  { number: 18, nameArabic: 'الكهف', nameEnglish: 'Al-Kahf', totalAyahs: 110, revelationType: 'Meccan' },
  { number: 19, nameArabic: 'مريم', nameEnglish: 'Maryam', totalAyahs: 98, revelationType: 'Meccan' },
  { number: 20, nameArabic: 'طه', nameEnglish: 'Taha', totalAyahs: 135, revelationType: 'Meccan' },
  { number: 21, nameArabic: 'الأنبياء', nameEnglish: 'Al-Anbiya', totalAyahs: 112, revelationType: 'Meccan' },
  { number: 22, nameArabic: 'الحج', nameEnglish: 'Al-Hajj', totalAyahs: 78, revelationType: 'Medinan' },
  { number: 23, nameArabic: 'المؤمنون', nameEnglish: "Al-Mu'minun", totalAyahs: 118, revelationType: 'Meccan' },
  { number: 24, nameArabic: 'النور', nameEnglish: 'An-Nur', totalAyahs: 64, revelationType: 'Medinan' },
  { number: 25, nameArabic: 'الفرقان', nameEnglish: 'Al-Furqan', totalAyahs: 77, revelationType: 'Meccan' },
  { number: 26, nameArabic: 'الشعراء', nameEnglish: "Ash-Shu'ara", totalAyahs: 227, revelationType: 'Meccan' },
  { number: 27, nameArabic: 'النمل', nameEnglish: 'An-Naml', totalAyahs: 93, revelationType: 'Meccan' },
  { number: 28, nameArabic: 'القصص', nameEnglish: 'Al-Qasas', totalAyahs: 88, revelationType: 'Meccan' },
  { number: 29, nameArabic: 'العنكبوت', nameEnglish: 'Al-Ankabut', totalAyahs: 69, revelationType: 'Meccan' },
  { number: 30, nameArabic: 'الروم', nameEnglish: 'Ar-Rum', totalAyahs: 60, revelationType: 'Meccan' },
  { number: 31, nameArabic: 'لقمان', nameEnglish: 'Luqman', totalAyahs: 34, revelationType: 'Meccan' },
  { number: 32, nameArabic: 'السجدة', nameEnglish: 'As-Sajdah', totalAyahs: 30, revelationType: 'Meccan' },
  { number: 33, nameArabic: 'الأحزاب', nameEnglish: 'Al-Ahzab', totalAyahs: 73, revelationType: 'Medinan' },
  { number: 34, nameArabic: 'سبأ', nameEnglish: 'Saba', totalAyahs: 54, revelationType: 'Meccan' },
  { number: 35, nameArabic: 'فاطر', nameEnglish: 'Fatir', totalAyahs: 45, revelationType: 'Meccan' },
  { number: 36, nameArabic: 'يس', nameEnglish: 'Ya-Sin', totalAyahs: 83, revelationType: 'Meccan' },
  { number: 37, nameArabic: 'الصافات', nameEnglish: 'As-Saffat', totalAyahs: 182, revelationType: 'Meccan' },
  { number: 38, nameArabic: 'ص', nameEnglish: 'Sad', totalAyahs: 88, revelationType: 'Meccan' },
  { number: 39, nameArabic: 'الزمر', nameEnglish: 'Az-Zumar', totalAyahs: 75, revelationType: 'Meccan' },
  { number: 40, nameArabic: 'غافر', nameEnglish: 'Ghafir', totalAyahs: 85, revelationType: 'Meccan' },
  { number: 41, nameArabic: 'فصلت', nameEnglish: 'Fussilat', totalAyahs: 54, revelationType: 'Meccan' },
  { number: 42, nameArabic: 'الشورى', nameEnglish: 'Ash-Shura', totalAyahs: 53, revelationType: 'Meccan' },
  { number: 43, nameArabic: 'الزخرف', nameEnglish: 'Az-Zukhruf', totalAyahs: 89, revelationType: 'Meccan' },
  { number: 44, nameArabic: 'الدخان', nameEnglish: 'Ad-Dukhan', totalAyahs: 59, revelationType: 'Meccan' },
  { number: 45, nameArabic: 'الجاثية', nameEnglish: 'Al-Jathiyah', totalAyahs: 37, revelationType: 'Meccan' },
  { number: 46, nameArabic: 'الأحقاف', nameEnglish: 'Al-Ahqaf', totalAyahs: 35, revelationType: 'Meccan' },
  { number: 47, nameArabic: 'محمد', nameEnglish: 'Muhammad', totalAyahs: 38, revelationType: 'Medinan' },
  { number: 48, nameArabic: 'الفتح', nameEnglish: 'Al-Fath', totalAyahs: 29, revelationType: 'Medinan' },
  { number: 49, nameArabic: 'الحجرات', nameEnglish: 'Al-Hujurat', totalAyahs: 18, revelationType: 'Medinan' },
  { number: 50, nameArabic: 'ق', nameEnglish: 'Qaf', totalAyahs: 45, revelationType: 'Meccan' },
  { number: 51, nameArabic: 'الذاريات', nameEnglish: 'Adh-Dhariyat', totalAyahs: 60, revelationType: 'Meccan' },
  { number: 52, nameArabic: 'الطور', nameEnglish: 'At-Tur', totalAyahs: 49, revelationType: 'Meccan' },
  { number: 53, nameArabic: 'النجم', nameEnglish: 'An-Najm', totalAyahs: 62, revelationType: 'Meccan' },
  { number: 54, nameArabic: 'القمر', nameEnglish: 'Al-Qamar', totalAyahs: 55, revelationType: 'Meccan' },
  { number: 55, nameArabic: 'الرحمن', nameEnglish: 'Ar-Rahman', totalAyahs: 78, revelationType: 'Medinan' },
  { number: 56, nameArabic: 'الواقعة', nameEnglish: "Al-Waqi'ah", totalAyahs: 96, revelationType: 'Meccan' },
  { number: 57, nameArabic: 'الحديد', nameEnglish: 'Al-Hadid', totalAyahs: 29, revelationType: 'Medinan' },
  { number: 58, nameArabic: 'المجادلة', nameEnglish: 'Al-Mujadila', totalAyahs: 22, revelationType: 'Medinan' },
  { number: 59, nameArabic: 'الحشر', nameEnglish: 'Al-Hashr', totalAyahs: 24, revelationType: 'Medinan' },
  { number: 60, nameArabic: 'الممتحنة', nameEnglish: 'Al-Mumtahanah', totalAyahs: 13, revelationType: 'Medinan' },
  { number: 61, nameArabic: 'الصف', nameEnglish: 'As-Saf', totalAyahs: 14, revelationType: 'Medinan' },
  { number: 62, nameArabic: 'الجمعة', nameEnglish: "Al-Jumu'ah", totalAyahs: 11, revelationType: 'Medinan' },
  { number: 63, nameArabic: 'المنافقون', nameEnglish: 'Al-Munafiqun', totalAyahs: 11, revelationType: 'Medinan' },
  { number: 64, nameArabic: 'التغابن', nameEnglish: 'At-Taghabun', totalAyahs: 18, revelationType: 'Medinan' },
  { number: 65, nameArabic: 'الطلاق', nameEnglish: 'At-Talaq', totalAyahs: 12, revelationType: 'Medinan' },
  { number: 66, nameArabic: 'التحريم', nameEnglish: 'At-Tahrim', totalAyahs: 12, revelationType: 'Medinan' },
  { number: 67, nameArabic: 'الملك', nameEnglish: 'Al-Mulk', totalAyahs: 30, revelationType: 'Meccan' },
  { number: 68, nameArabic: 'القلم', nameEnglish: 'Al-Qalam', totalAyahs: 52, revelationType: 'Meccan' },
  { number: 69, nameArabic: 'الحاقة', nameEnglish: 'Al-Haqqah', totalAyahs: 52, revelationType: 'Meccan' },
  { number: 70, nameArabic: 'المعارج', nameEnglish: "Al-Ma'arij", totalAyahs: 44, revelationType: 'Meccan' },
  { number: 71, nameArabic: 'نوح', nameEnglish: 'Nuh', totalAyahs: 28, revelationType: 'Meccan' },
  { number: 72, nameArabic: 'الجن', nameEnglish: 'Al-Jinn', totalAyahs: 28, revelationType: 'Meccan' },
  { number: 73, nameArabic: 'المزمل', nameEnglish: 'Al-Muzzammil', totalAyahs: 20, revelationType: 'Meccan' },
  { number: 74, nameArabic: 'المدثر', nameEnglish: 'Al-Muddaththir', totalAyahs: 56, revelationType: 'Meccan' },
  { number: 75, nameArabic: 'القيامة', nameEnglish: 'Al-Qiyamah', totalAyahs: 40, revelationType: 'Meccan' },
  { number: 76, nameArabic: 'الانسان', nameEnglish: 'Al-Insan', totalAyahs: 31, revelationType: 'Medinan' },
  { number: 77, nameArabic: 'المرسلات', nameEnglish: 'Al-Mursalat', totalAyahs: 50, revelationType: 'Meccan' },
  { number: 78, nameArabic: 'النبأ', nameEnglish: 'An-Naba', totalAyahs: 40, revelationType: 'Meccan' },
  { number: 79, nameArabic: 'النازعات', nameEnglish: "An-Nazi'at", totalAyahs: 46, revelationType: 'Meccan' },
  { number: 80, nameArabic: 'عبس', nameEnglish: 'Abasa', totalAyahs: 42, revelationType: 'Meccan' },
  { number: 81, nameArabic: 'التكوير', nameEnglish: 'At-Takwir', totalAyahs: 29, revelationType: 'Meccan' },
  { number: 82, nameArabic: 'الإنفطار', nameEnglish: 'Al-Infitar', totalAyahs: 19, revelationType: 'Meccan' },
  { number: 83, nameArabic: 'المطففين', nameEnglish: 'Al-Mutaffifin', totalAyahs: 36, revelationType: 'Meccan' },
  { number: 84, nameArabic: 'الإنشقاق', nameEnglish: 'Al-Inshiqaq', totalAyahs: 25, revelationType: 'Meccan' },
  { number: 85, nameArabic: 'البروج', nameEnglish: 'Al-Buruj', totalAyahs: 22, revelationType: 'Meccan' },
  { number: 86, nameArabic: 'الطارق', nameEnglish: 'At-Tariq', totalAyahs: 17, revelationType: 'Meccan' },
  { number: 87, nameArabic: 'الأعلى', nameEnglish: "Al-A'la", totalAyahs: 19, revelationType: 'Meccan' },
  { number: 88, nameArabic: 'الغاشية', nameEnglish: 'Al-Ghashiyah', totalAyahs: 26, revelationType: 'Meccan' },
  { number: 89, nameArabic: 'الفجر', nameEnglish: 'Al-Fajr', totalAyahs: 30, revelationType: 'Meccan' },
  { number: 90, nameArabic: 'البلد', nameEnglish: 'Al-Balad', totalAyahs: 20, revelationType: 'Meccan' },
  { number: 91, nameArabic: 'الشمس', nameEnglish: 'Ash-Shams', totalAyahs: 15, revelationType: 'Meccan' },
  { number: 92, nameArabic: 'الليل', nameEnglish: 'Al-Layl', totalAyahs: 21, revelationType: 'Meccan' },
  { number: 93, nameArabic: 'الضحى', nameEnglish: 'Ad-Duha', totalAyahs: 11, revelationType: 'Meccan' },
  { number: 94, nameArabic: 'الشرح', nameEnglish: 'Ash-Sharh', totalAyahs: 8, revelationType: 'Meccan' },
  { number: 95, nameArabic: 'التين', nameEnglish: 'At-Tin', totalAyahs: 8, revelationType: 'Meccan' },
  { number: 96, nameArabic: 'العلق', nameEnglish: 'Al-Alaq', totalAyahs: 19, revelationType: 'Meccan' },
  { number: 97, nameArabic: 'القدر', nameEnglish: 'Al-Qadr', totalAyahs: 5, revelationType: 'Meccan' },
  { number: 98, nameArabic: 'البينة', nameEnglish: 'Al-Bayyinah', totalAyahs: 8, revelationType: 'Medinan' },
  { number: 99, nameArabic: 'الزلزلة', nameEnglish: 'Az-Zalzalah', totalAyahs: 8, revelationType: 'Medinan' },
  { number: 100, nameArabic: 'العاديات', nameEnglish: 'Al-Adiyat', totalAyahs: 11, revelationType: 'Meccan' },
  { number: 101, nameArabic: 'القارعة', nameEnglish: "Al-Qari'ah", totalAyahs: 11, revelationType: 'Meccan' },
  { number: 102, nameArabic: 'التكاثر', nameEnglish: 'At-Takathur', totalAyahs: 8, revelationType: 'Meccan' },
  { number: 103, nameArabic: 'العصر', nameEnglish: 'Al-Asr', totalAyahs: 3, revelationType: 'Meccan' },
  { number: 104, nameArabic: 'الهمزة', nameEnglish: 'Al-Humazah', totalAyahs: 9, revelationType: 'Meccan' },
  { number: 105, nameArabic: 'الفيل', nameEnglish: 'Al-Fil', totalAyahs: 5, revelationType: 'Meccan' },
  { number: 106, nameArabic: 'قريش', nameEnglish: 'Quraysh', totalAyahs: 4, revelationType: 'Meccan' },
  { number: 107, nameArabic: 'الماعون', nameEnglish: "Al-Ma'un", totalAyahs: 7, revelationType: 'Meccan' },
  { number: 108, nameArabic: 'الكوثر', nameEnglish: 'Al-Kawthar', totalAyahs: 3, revelationType: 'Meccan' },
  { number: 109, nameArabic: 'الكافرون', nameEnglish: 'Al-Kafirun', totalAyahs: 6, revelationType: 'Meccan' },
  { number: 110, nameArabic: 'النصر', nameEnglish: 'An-Nasr', totalAyahs: 3, revelationType: 'Medinan' },
  { number: 111, nameArabic: 'المسد', nameEnglish: 'Al-Masad', totalAyahs: 5, revelationType: 'Meccan' },
  { number: 112, nameArabic: 'الإخلاص', nameEnglish: 'Al-Ikhlas', totalAyahs: 4, revelationType: 'Meccan' },
  { number: 113, nameArabic: 'الفلق', nameEnglish: 'Al-Falaq', totalAyahs: 5, revelationType: 'Meccan' },
  { number: 114, nameArabic: 'الناس', nameEnglish: 'An-Nas', totalAyahs: 6, revelationType: 'Meccan' },
];
